language: node_js
node_js:
  - "4"
  - "6"
  - "8"
  - "10"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - g++-4.8-multilib
    - gcc-multilib
before_install:
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
    - $CXX --version
